# The URL the site will be built for
base_url = "https://codingdaniel.pages.dev"

title = "Daniel Chen"
author = "Daniel Chen"

theme = "linkita"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

default_language = "en"

generate_sitemap = true

generate_feeds = true

# The filenames to use for the feeds. Used as the template filenames, too.
# Defaults to ["atom.xml"], which has a built-in template that renders an Atom 1.0 feed.
# There is also a built-in template "rss.xml" that renders an RSS 2.0 feed.
feed_filenames = ["atom.xml"]

taxonomies = [
	{ name = "tags", feed = true }
]

[languages.zh]
title = "Daniel Chen"
build_search_index = false
generate_feeds = true
feed_filenames = ["atom.xml"]
taxonomies = [
	{ name = "tags", feed = true }
]

[markdown]
github_alerts = true
insert_anchor_links = "heading"
smart_punctuation = true

[markdown.highlighting]
# Kita theme supports both "inline" and "class" modes.
style = "inline"

# If light/dark themes are set, the code highlighting theme will follow Kita theme's light/dark mode.
light_theme = "light-plus"
dark_theme = "github-dark-default"

# A list of files for additional JSON TextMate grammars
extra_grammars = []

# A list of files for additional JSON TextMate themes
extra_themes = []

# The Kita theme config.
[extra]
# Enable KaTex math formula support globally.
math = false

# Enable mermaid support globally.
mermaid = false

# Enable comment support globally.
comment = true

# Title separator.
title_separator = " | "

# The top menu.
# See "extra.menus".
header_menu_name = "header_links"

# See "extra.menus".
menu_i18n = true

# Enable floating table of contents on the right side of the post page.
side_toc = true

# Enable table of contents on all pages.
# If not set, toc is enabled only on posts.
# If set to false, toc is disabled on all pages.
# Type: boolean or object
toc = true

[extra.menus]
header_links = [
    { url = "@base/archive/", name = "Archive" },
    { url = "@base/tags/", name = "Tags" },
    { url = "@base/about/", name = "About" },
]

[extra.profiles.danielchen]
name = "Daniel Chen"
bio = "I'm a game/engine developer focusing on graphics programming, game networking, performance optimizations."

# Social icons.
# "name" should be the file name of "static/icons/*.svg" or
# the icon name of https://simpleicons.org/
# "url" supports "@base".
# Other variables: "urls", "title", "titles".
social = [
    { name = "github", url = "https://github.com/CodingDaniel1" },
    { name = "steam", url = "https://steamcommunity.com/profiles/76561198983573782/" },
    { name = "youtube", url = "https://www.youtube.com/@codingdaniel" },
]


# [[extra.menu]]
# name = "Archive"
# url = "@/pages/archive.md"

[extra.footer]
since = 2026

# The giscus comment options, only available when comment is enabled.
[extra.giscus]
repo = "CodingDaniel1/codingdaniel"
repo_id = "R_kgDOUuIqmA"
category = "General"
category_id = "DIC_kwDOUuIqmM4DGf9y"
mapping = "pathname"
strict = 1
reactions_enabled = 1
emit_metadata = 0
input_position = "top"
theme = "preferred_color_scheme"
lang = "en"
loading = "lazy"
